version: '3.1'

services:

    mongo:
        image: mongo
        restart: always
        ports:
            - 8080:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: pass

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass
            ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo:27017/

    node-server:
        image: node-server
        build:
            context: ./
            dockerfile: dockerfile.node-server
        ports:
            - 3000:3000
        environment:
            - PORT=3000
            - DB_URL=mongodb://admin:pass@mongo:27017/users?authSource=admin
            - DOMAIN=http://localhost:3000
        depends_on:
            - mongo
